In [3]:
#Problem1
#Task1
import numpy as np
empty_array = np.empty((2, 2))
print("Empty array (2x2):\n", empty_array)

Empty array (2x2):
 [[1.06481653e+248 5.33043819e+228]
 [3.83500422e+151 6.91080933e-315]]


In [4]:
#Task2
ones_array = np.ones((4, 2))
print("All ones array (4x2):\n", ones_array)

All ones array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
#Task3
filled_array = np.full((3, 4), 5)
print("Array filled with 5s (3x4):\n", filled_array)

Array filled with 5s (3x4):
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [6]:
#Task4
original_array_for_zeros = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
zeros_like_array = np.zeros_like(original_array_for_zeros)
print("Zeros like array:\n", zeros_like_array)

Zeros like array:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
#Task5
original_array_for_ones = np.array([[10, 20], [30, 40]], dtype=int)
ones_like_array = np.ones_like(original_array_for_ones)
print("Ones like array:\n", ones_like_array)

Ones like array:
 [[1 1]
 [1 1]]


In [8]:
#Task6
new_list = [1, 2, 3, 4]
numpy_array_from_list = np.array(new_list)
print("NumPy array from list:\n", numpy_array_from_list)
print("Type of NumPy array:\n", type(numpy_array_from_list))

NumPy array from list:
 [1 2 3 4]
Type of NumPy array:
 <class 'numpy.ndarray'>


In [9]:
#Problem2
#Task1
array_range = np.arange(10, 50)
print("Array with values from 10 to 49:\n", array_range)

Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
#Task2
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 matrix with values from 0 to 8:\n", matrix_3x3)

3x3 matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
#Task3
identity_matrix = np.eye(3)
print("3x3 identity matrix:\n", identity_matrix)

3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
#Task4
random_array_30 = np.random.random(30)
mean_of_array = random_array_30.mean()
print("Random array of size 30:\n", random_array_30)
print("Mean of the array:\n", mean_of_array)

Random array of size 30:
 [0.86713759 0.19529092 0.24288154 0.37113008 0.3682525  0.93340283
 0.26532572 0.42233497 0.56997258 0.66814338 0.51004884 0.44352891
 0.54018707 0.99260521 0.47055115 0.82305802 0.49581371 0.21259134
 0.38036037 0.55187576 0.87087129 0.21242802 0.87872029 0.91547627
 0.30496458 0.33479388 0.91635148 0.06621439 0.53443195 0.03386223]
Mean of the array:
 0.5130868955010927


In [13]:
#Task5
random_array_10x10 = np.random.random((10, 10))
min_value = random_array_10x10.min()
max_value = random_array_10x10.max()
print("10x10 random array:\n", random_array_10x10)
print("Minimum value:\n", min_value)
print("Maximum value:\n", max_value)

10x10 random array:
 [[0.40801949 0.79514712 0.13371646 0.98950944 0.66169696 0.08357945
  0.08151932 0.9605502  0.71743795 0.24643276]
 [0.23464854 0.69856363 0.68059241 0.08073633 0.26261938 0.85627362
  0.71504885 0.75943592 0.77059406 0.2218652 ]
 [0.44077592 0.63380349 0.77456361 0.64642666 0.33803113 0.74773836
  0.77387215 0.95092801 0.91785393 0.40641576]
 [0.50402677 0.79915121 0.13653139 0.05287767 0.9105434  0.91806286
  0.42197587 0.56994867 0.77561769 0.48409054]
 [0.899773   0.23182841 0.14417325 0.42725647 0.42117655 0.36221937
  0.87034218 0.04594172 0.87471775 0.88432775]
 [0.10761979 0.34779924 0.25683745 0.28977251 0.59073656 0.21666044
  0.39869707 0.56274039 0.48689828 0.24233942]
 [0.48373669 0.1536191  0.42902483 0.20745596 0.46902176 0.81651352
  0.07060861 0.87354249 0.06641025 0.90640424]
 [0.56634947 0.13915434 0.06474974 0.83746432 0.45909747 0.50495678
  0.21076576 0.5402814  0.49777176 0.72328743]
 [0.97892847 0.15129403 0.62198558 0.00585318 0.56908083 0.

In [14]:
#Task6
zero_array = np.zeros(10)
zero_array[4] = 1 # Python uses 0-based indexing, so the 5th element is at index 4
print("Zero array with 5th element replaced by 1:\n", zero_array)

Zero array with 5th element replaced by 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [15]:
#Task7
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Reversed array:\n", reversed_arr)

Reversed array:
 [0 4 0 0 2 1]


In [16]:
#Task8
rows, cols = 5, 5 # Example dimensions
border_array = np.ones((rows, cols))
border_array[1:-1, 1:-1] = 0
print("Array with 1s on border and 0s inside:\n", border_array)

Array with 1s on border and 0s inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
#Task9
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 checkerboard pattern:\n", checkerboard)

8x8 checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [18]:
#Problem3
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print("Array x:\n", x)
print("Array y:\n", y)
print("Array v:\n", v)
print("Array w:\n", w)

Array x:
 [[1 2]
 [3 5]]
Array y:
 [[5 6]
 [7 8]]
Array v:
 [ 9 10]
Array w:
 [11 12]


In [19]:
#Task1
array_sum = x + y
print("Sum of x and y:\n", array_sum)

Sum of x and y:
 [[ 6  8]
 [10 13]]


In [20]:
#Task2
array_difference = x - y
print("Difference of x and y:\n", array_difference)

Difference of x and y:
 [[-4 -4]
 [-4 -3]]


In [21]:
#Task3
integer_factor = 3
array_product = x * integer_factor
print(f"Product of x with {integer_factor}:\n", array_product)

Product of x with 3:
 [[ 3  6]
 [ 9 15]]


In [22]:
#Task4
array_squared = x**2
print("Square of each element in x:\n", array_squared)

Square of each element in x:
 [[ 1  4]
 [ 9 25]]


In [23]:
#Task5
dot_vw = np.dot(v, w)
print("Dot product of v and w:\n", dot_vw)

dot_xv = np.dot(x, v)
print("Dot product of x and v:\n", dot_xv)

dot_xy = np.dot(x, y)
print("Dot product of x and y:\n", dot_xy)

Dot product of v and w:
 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


In [24]:
#Task6
concat_xy_rows = np.vstack((x, y)) # or np.concatenate((x, y), axis=0)
print("Concatenating x and y along rows:\n", concat_xy_rows)

# v and w are 1D arrays, to concatenate along columns, they need to be reshaped to 2D
concat_vw_cols = np.hstack((v[:, np.newaxis], w[:, np.newaxis])) # or np.concatenate((v[:, np.newaxis], w[:, np.newaxis]), axis=1)
print("Concatenating v and w along columns:\n", concat_vw_cols)

Concatenating x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenating v and w along columns:
 [[ 9 11]
 [10 12]]


In [25]:
#Task7
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("Concatenation of x and v:\n", concat_xv)
except ValueError as e:
    print(f"Caught an error during concatenation: {e}")

Caught an error during concatenation: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


# Explanation of Error:
The error occurs because NumPy requires arrays to have the same number of dimensions when using concatenate, vstack, or hstack.
Here, x is 2D (shape (2,2)) while v is 1D (shape (2,)), so they cannot be combined directly.

In [26]:
#Problem4
#Task1
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

print("Array A:\n", A)
print("Array B:\n", B)

Array A:
 [[3 4]
 [7 8]]
Array B:
 [[5 3]
 [2 1]]


In [27]:
#Question1
A_inv = np.linalg.inv(A)
product_AA_inv = np.dot(A, A_inv)

print("Inverse of A (A⁻¹):\n", A_inv)
print("Product A * A⁻¹:\n", product_AA_inv)
print("Is A * A⁻¹ approximately equal to Identity matrix?\n", np.allclose(product_AA_inv, np.eye(A.shape[0])))

Inverse of A (A⁻¹):
 [[-2.    1.  ]
 [ 1.75 -0.75]]
Product A * A⁻¹:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is A * A⁻¹ approximately equal to Identity matrix?
 True


In [28]:
#Question2
AB = np.dot(A, B)
BA = np.dot(B, A)

print("Product AB:\n", AB)
print("Product BA:\n", BA)
print("Is AB equal to BA?\n", np.array_equal(AB, BA))

Product AB:
 [[23 13]
 [51 29]]
Product BA:
 [[36 44]
 [13 16]]
Is AB equal to BA?
 False


In [29]:
#Question3
AB_transpose = (np.dot(A, B)).T
B_transpose_A_transpose = np.dot(B.T, A.T)

print("(AB)ᵀ:\n", AB_transpose)
print("BᵀAᵀ:\n", B_transpose_A_transpose)
print("Is (AB)ᵀ approximately equal to BᵀAᵀ?\n", np.allclose(AB_transpose, B_transpose_A_transpose))

(AB)ᵀ:
 [[23 51]
 [13 29]]
BᵀAᵀ:
 [[23 51]
 [13 29]]
Is (AB)ᵀ approximately equal to BᵀAᵀ?
 True


# Task2
The system of linear equations is:

2x - 3y + z = -1
x - y + 2z = -3
3x + y - z = 9

This can be represented in matrix form as AX = B, where:

A = [[2, -3, 1],
     [1, -1, 2],
     [3,  1, -1]]

X = [[x],
     [y],
     [z]]

B = [[-1],
     [-3],
     [9]]

In [30]:
# Represent the coefficients matrix A
A_coeffs = np.array([[2, -3, 1],
                     [1, -1, 2],
                     [3,  1, -1]])

# Represent the constants vector B
B_constants = np.array([[-1],
                        [-3],
                        [9]])

print("Coefficient Matrix A:\n", A_coeffs)
print("Constants Vector B:\n", B_constants)

Coefficient Matrix A:
 [[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
Constants Vector B:
 [[-1]
 [-3]
 [ 9]]


In [31]:
#Task3
# Calculate the inverse of A
A_coeffs_inv = np.linalg.inv(A_coeffs)

print("Inverse of A (A⁻¹):\n", A_coeffs_inv)

# Solve for X = A⁻¹B
X_solution = np.dot(A_coeffs_inv, B_constants)

print("Solution for X (x, y, z):\n", X_solution)

x_val = X_solution[0][0]
y_val = X_solution[1][0]
z_val = X_solution[2][0]

print(f"The solution is: x = {x_val:.2f}, y = {y_val:.2f}, z = {z_val:.2f}")

Inverse of A (A⁻¹):
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]
Solution for X (x, y, z):
 [[ 2.]
 [ 1.]
 [-2.]]
The solution is: x = 2.00, y = 1.00, z = -2.00
